"""empty message

Revision ID: 977da856afe8
Revises: ece7b59e96d7
Create Date: 2017-03-15 19:51:24.823721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977da856afe8'
down_revision = 'ece7b59e96d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture')
    # ### end Alembic commands ###
